#166873552 Implement logfile rotate
AndelaOSP/Andela-Socials pull request #246
Opened 2019-07-08 18:05 UTC by kafuuma

#### What Does This PR Do?
- Implement logfile rotate for logs

#### Description Of Task To Be Completed
- Add log file to store log records
- Specify location of log file to be /var/log/andela_socials/ in production and /tmp/log/andela_socials/ in 
  development

#### How can this be manually tested?

#### What are the relevant pivotal tracker stories?
[#166873552](https://www.pivotaltracker.com/story/show/166873552)
[#166873566](https://www.pivotaltracker.com/story/show/166873566)
#### Screenshot(s)

2019-07-11 09:56 UTC, andrewinsoul submitted a review, later dismissed

2019-07-11 09:56 UTC, andrewinsoul commented on .circleci/config.yml
> +                  - POSTGRES_PASSWORD: $DB_PASSWORD
The env variable did not reflect in the file and that is why probably it did not show up on CircleCi

2019-07-16 10:09 UTC, brianbirir requested changes

2019-07-16 10:09 UTC, brianbirir commented on .circleci/config.yml
> +                      python server/manage.py test --snapshot-update server/api/tests/ server/graphql_schemas/tests/  --keepdb
Please remove the `--keep-db` flag. The test database should ideally be deleted.

2019-07-16 10:09 UTC, brianbirir commented on client/assets/components/navbar.scss
>  @import '../colors.scss';
The focus of this PR is to change log file location and not editing or updating the client side of the application. Please revert.

2019-07-16 10:09 UTC, brianbirir commented on server/a_socials/settings/dev.py
> +# load logg settings
Please provide correct spelling i.e. should be **log**

2019-07-16 10:16 UTC, brianbirir commented
@kafuuma this PR should focus on one story only but is currently associated with two Pivotal Tracker stories. The appropriate story is https://www.pivotaltracker.com/n/projects/2174978/stories/166873552.

Please change the PR title to reflect this i.e. **#166873552 Change log file location** and update the description. Also complete the section on **How can this be manually tested?** in the PR description section. Thanks.

2019-07-16 10:26 UTC, brianbirir commented
@kafuuma in regards to log file rotation, this should be implemented server side in the Linux environment and in the Docker:

https://medium.com/@Quigley_Ja/rotating-docker-logs-keeping-your-overlay-folder-small-40cfa2155412
https://markuscisler.com/rotate-docker-logs/

For log rotate,  please create a separate PR.

2019-07-19 06:25 UTC, brianbirir requested changes

2019-07-19 06:25 UTC, brianbirir commented on docker/server/Dockerfile
> +RUN mkdir /tmp/log &&  mkdir /tmp/log/andela_socials/
this can be done with one command:

```
mkdir -p /tmp/log/andela_socials
```

please update @kafuuma

2019-07-19 07:02 UTC, brianbirir commented on server/a_socials/settings/logger_settings.py
> +os.makedirs('/tmp/log/andela_socials', mode=0o777, exist_ok=True)
@kafuuma what's the purpose of this? I thought it's already been taken care of in `docker/server/Dockerfile` line 17

2019-07-19 07:15 UTC, brianbirir commented
Works as expected from the Docker perspective. Just a few changes need to be made @kafuuma

2019-07-19 11:59 UTC, brianbirir commented
Looks good.

2019-07-19 12:00 UTC, merged